-- ========================================
-- ENVIRONMENTAL PLATFORM - PHASE 7-11: COMPLETE SYSTEM
-- Events, Petitions, E-commerce, Quiz & Gamification
-- Version: 3.0 Final Implementation
-- ========================================

USE environmental_platform;

SET FOREIGN_KEY_CHECKS = 0;

-- ========================================
-- PHASE 7: EVENTS & ACTIVITIES SYSTEM
-- ========================================

CREATE TABLE IF NOT EXISTS events (
    event_id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description LONGTEXT,
    short_description TEXT,
    event_type ENUM('workshop', 'cleanup', 'conference', 'competition', 'exhibition', 'webinar', 'training', 'volunteer', 'awareness') NOT NULL,
    event_mode ENUM('online', 'offline', 'hybrid') DEFAULT 'offline',
    organizer_id INT NOT NULL,
    co_organizers JSON,
    venue_name VARCHAR(255),
    venue_address TEXT,
    online_platform VARCHAR(100),
    meeting_link VARCHAR(500),
    latitude DECIMAL(10, 6),
    longitude DECIMAL(10, 6),
    start_date DATETIME NOT NULL,
    end_date DATETIME NOT NULL,
    timezone VARCHAR(50) DEFAULT 'Asia/Ho_Chi_Minh',
    max_participants INT,
    current_participants INT DEFAULT 0,
    min_participants INT DEFAULT 1,
    registration_fee DECIMAL(10,2) DEFAULT 0,
    registration_deadline DATETIME,
    age_restriction ENUM('all_ages', '18+', '16+', '13+') DEFAULT 'all_ages',
    skill_level ENUM('beginner', 'intermediate', 'advanced', 'all_levels') DEFAULT 'all_levels',
    agenda JSON,
    materials_needed TEXT,
    what_to_bring TEXT,
    environmental_benefits TEXT,
    carbon_offset_kg DECIMAL(10,3) DEFAULT 0,
    points_reward INT DEFAULT 10,
    certificate_provided BOOLEAN DEFAULT FALSE,
    qr_code_data VARCHAR(500),
    check_in_enabled BOOLEAN DEFAULT TRUE,
    status ENUM('draft', 'published', 'cancelled', 'completed', 'postponed') DEFAULT 'draft',
    featured_image VARCHAR(255),
    gallery_images JSON,
    video_url VARCHAR(500),
    tags JSON,
    is_featured BOOLEAN DEFAULT FALSE,
    is_verified BOOLEAN DEFAULT FALSE,
    requires_approval BOOLEAN DEFAULT FALSE,
    approval_notes TEXT,
    weather_dependency BOOLEAN DEFAULT FALSE,
    backup_plan TEXT,
    contact_email VARCHAR(100),
    contact_phone VARCHAR(20),
    social_media_links JSON,
    partner_organizations JSON,
    sponsorships JSON,
    budget DECIMAL(12,2),
    expenses JSON,
    feedback_form_url VARCHAR(500),
    follow_up_actions TEXT,
    impact_report TEXT,
    media_coverage JSON,
    view_count INT DEFAULT 0,
    share_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    published_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    INDEX idx_status_date (status, start_date),
    INDEX idx_location (latitude, longitude),
    INDEX idx_organizer (organizer_id, status),
    INDEX idx_type_mode (event_type, event_mode),
    INDEX idx_featured (is_featured, start_date DESC),
    INDEX idx_registration_deadline (registration_deadline),
    FULLTEXT(title, description, venue_name, tags)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS event_registrations (
    registration_id INT PRIMARY KEY AUTO_INCREMENT,
    event_id INT NOT NULL,
    user_id INT NOT NULL,
    registration_number VARCHAR(50) UNIQUE NOT NULL,
    registration_status ENUM('registered', 'attended', 'cancelled', 'no_show', 'waitlisted') DEFAULT 'registered',
    registration_fee_paid DECIMAL(10,2) DEFAULT 0,
    payment_status ENUM('pending', 'paid', 'refunded', 'waived') DEFAULT 'pending',
    payment_method VARCHAR(50),
    payment_transaction_id VARCHAR(100),
    check_in_status ENUM('not_checked_in', 'checked_in', 'checked_out') DEFAULT 'not_checked_in',
    check_in_time TIMESTAMP NULL,
    check_out_time TIMESTAMP NULL,
    check_in_method ENUM('qr_code', 'manual', 'facial_recognition', 'app') DEFAULT 'manual',
    attendance_percentage DECIMAL(5,2) DEFAULT 0,
    participation_rating INT DEFAULT 0,
    special_requirements TEXT,
    dietary_restrictions VARCHAR(255),
    emergency_contact JSON,
    participant_info JSON,
    feedback_rating INT,
    feedback_comment TEXT,
    certificate_issued BOOLEAN DEFAULT FALSE,
    certificate_url VARCHAR(500),
    points_earned INT DEFAULT 0,
    carbon_saved_kg DECIMAL(10,3) DEFAULT 0,
    source VARCHAR(100),
    referred_by INT,
    notes TEXT,
    cancellation_reason TEXT,
    cancelled_at TIMESTAMP NULL,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_event_status (event_id, registration_status),
    INDEX idx_user_registrations (user_id, registered_at),
    INDEX idx_registration_number (registration_number),
    INDEX idx_check_in (check_in_status, check_in_time),
    UNIQUE KEY unique_event_user (event_id, user_id)
) ENGINE=InnoDB;

-- ========================================
-- PHASE 8: PETITIONS & CAMPAIGNS SYSTEM
-- ========================================

CREATE TABLE IF NOT EXISTS petitions (
    petition_id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    summary TEXT NOT NULL,
    description LONGTEXT NOT NULL,
    petition_type ENUM('environmental', 'policy', 'corporate', 'community', 'global', 'climate', 'wildlife', 'pollution') NOT NULL,
    target_type ENUM('government', 'corporation', 'organization', 'individual', 'multiple') NOT NULL,
    target_entities JSON NOT NULL,
    creator_id INT NOT NULL,
    organization_id INT,
    category_id INT,
    location_scope ENUM('local', 'city', 'province', 'national', 'regional', 'global') DEFAULT 'national',
    affected_locations JSON,
    signature_goal INT NOT NULL,
    current_signatures INT DEFAULT 0,
    verified_signatures INT DEFAULT 0,
    supporter_comments INT DEFAULT 0,
    share_count INT DEFAULT 0,
    view_count INT DEFAULT 0,
    media_coverage JSON,
    featured_image VARCHAR(255),
    video_url VARCHAR(500),
    supporting_documents JSON,
    impact_description TEXT,
    solution_proposed TEXT,
    timeline_proposed VARCHAR(255),
    budget_required DECIMAL(15, 2),
    endorsements JSON,
    opposition JSON,
    updates JSON,
    milestones JSON,
    status ENUM('draft', 'active', 'victory', 'closed', 'suspended', 'under_review') DEFAULT 'draft',
    victory_description TEXT,
    closed_reason TEXT,
    deadline DATE,
    tags JSON,
    is_featured BOOLEAN DEFAULT FALSE,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_notes TEXT,
    allow_anonymous_signatures BOOLEAN DEFAULT TRUE,
    require_id_verification BOOLEAN DEFAULT FALSE,
    email_updates_enabled BOOLEAN DEFAULT TRUE,
    auto_responses JSON,
    moderation_settings JSON,
    social_sharing_settings JSON,
    analytics_data JSON,
    seo_title VARCHAR(255),
    seo_description TEXT,
    seo_keywords JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    published_at TIMESTAMP NULL,
    victory_at TIMESTAMP NULL,
    INDEX idx_status_deadline (status, deadline),
    INDEX idx_creator (creator_id),
    INDEX idx_featured_active (is_featured, status),
    INDEX idx_signature_goal (signature_goal, current_signatures),
    INDEX idx_slug (slug),
    INDEX idx_type_scope (petition_type, location_scope),
    FULLTEXT(title, summary, description, tags)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS petition_signatures (
    signature_id INT PRIMARY KEY AUTO_INCREMENT,
    petition_id INT NOT NULL,
    user_id INT,
    signer_name VARCHAR(100) NOT NULL,
    signer_email VARCHAR(100),
    signer_phone VARCHAR(20),
    signer_location VARCHAR(100),
    signer_city VARCHAR(100),
    signer_country VARCHAR(50) DEFAULT 'Vietnam',
    postal_code VARCHAR(20),
    age_range ENUM('under_18', '18_25', '26_35', '36_45', '46_55', '56_65', 'over_65'),
    occupation VARCHAR(100),
    id_number VARCHAR(50),
    id_type ENUM('citizen_id', 'passport', 'driver_license'),
    comment TEXT,
    is_public BOOLEAN DEFAULT TRUE,
    is_anonymous BOOLEAN DEFAULT FALSE,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_method ENUM('email', 'sms', 'id_check', 'manual', 'social_login') DEFAULT 'email',
    verification_code VARCHAR(50),
    verified_at TIMESTAMP NULL,
    share_consent BOOLEAN DEFAULT TRUE,
    newsletter_consent BOOLEAN DEFAULT FALSE,
    data_processing_consent BOOLEAN DEFAULT TRUE,
    signature_source ENUM('website', 'mobile_app', 'social_media', 'email', 'offline', 'imported') DEFAULT 'website',
    campaign_source VARCHAR(100),
    utm_parameters JSON,
    ip_address VARCHAR(45),
    user_agent TEXT,
    device_info JSON,
    geolocation JSON,
    referred_by INT,
    influence_score INT DEFAULT 1,
    social_reach INT DEFAULT 0,
    follow_up_actions JSON,
    signed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_petition_verified (petition_id, is_verified),
    INDEX idx_petition_public (petition_id, is_public, signed_at DESC),
    INDEX idx_email (signer_email),
    INDEX idx_location (signer_city, signer_country),
    INDEX idx_verification (verification_method, is_verified),
    UNIQUE KEY unique_petition_email (petition_id, signer_email),
    UNIQUE KEY unique_petition_user (petition_id, user_id)
) ENGINE=InnoDB;

-- ========================================
-- PHASE 9: E-COMMERCE & MARKETPLACE SETUP
-- ========================================

CREATE TABLE IF NOT EXISTS product_brands (
    brand_id INT PRIMARY KEY AUTO_INCREMENT,
    brand_name VARCHAR(100) NOT NULL,
    brand_slug VARCHAR(100) UNIQUE NOT NULL,
    brand_name_local VARCHAR(100),
    company_name VARCHAR(255),
    description TEXT,
    story TEXT,
    logo_url VARCHAR(255),
    cover_image_url VARCHAR(255),
    website_url VARCHAR(255),
    social_media JSON,
    contact_info JSON,
    certifications JSON,
    sustainability_score INT DEFAULT 0,
    eco_certifications JSON,
    carbon_neutral BOOLEAN DEFAULT FALSE,
    founded_year YEAR,
    headquarters_location VARCHAR(100),
    employee_count INT,
    annual_revenue DECIMAL(15,2),
    sustainability_report_url VARCHAR(500),
    impact_metrics JSON,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_documents JSON,
    partner_since DATE,
    partnership_level ENUM('bronze', 'silver', 'gold', 'platinum') DEFAULT 'bronze',
    commission_rate DECIMAL(5,2) DEFAULT 10.00,
    is_active BOOLEAN DEFAULT TRUE,
    featured_priority INT DEFAULT 0,
    seo_title VARCHAR(255),
    seo_description TEXT,
    seo_keywords JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_sustainability (sustainability_score DESC, is_active),
    INDEX idx_partnership (partnership_level, is_active),
    INDEX idx_slug (brand_slug),
    FULLTEXT(brand_name, company_name, description)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sellers (
    seller_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    brand_id INT,
    business_name VARCHAR(255) NOT NULL,
    business_type ENUM('individual', 'company', 'cooperative', 'ngo', 'social_enterprise') NOT NULL,
    business_registration_number VARCHAR(100),
    tax_identification_number VARCHAR(100),
    description TEXT,
    business_address JSON NOT NULL,
    shipping_locations JSON,
    contact_person VARCHAR(100),
    contact_email VARCHAR(100) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    website_url VARCHAR(255),
    social_media JSON,
    business_license_url VARCHAR(500),
    certifications JSON,
    sustainability_practices TEXT,
    eco_initiatives JSON,
    carbon_footprint_data JSON,
    return_policy TEXT,
    shipping_policy TEXT,
    warranty_policy TEXT,
    customer_service_hours VARCHAR(255),
    payment_methods JSON,
    bank_account_info JSON,
    commission_rate DECIMAL(5,2) DEFAULT 15.00,
    seller_rating DECIMAL(3,2) DEFAULT 0,
    total_orders INT DEFAULT 0,
    total_sales DECIMAL(15,2) DEFAULT 0,
    total_products INT DEFAULT 0,
    response_time_hours INT DEFAULT 24,
    response_rate_percentage DECIMAL(5,2) DEFAULT 100,
    shipping_on_time_percentage DECIMAL(5,2) DEFAULT 100,
    account_status ENUM('pending', 'active', 'suspended', 'banned', 'under_review') DEFAULT 'pending',
    verification_status ENUM('unverified', 'pending', 'verified', 'rejected') DEFAULT 'unverified',
    verification_documents JSON,
    verification_notes TEXT,
    approved_at TIMESTAMP NULL,
    approved_by INT,
    last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_seller (user_id),
    INDEX idx_brand (brand_id),
    INDEX idx_status (account_status, verification_status),
    INDEX idx_rating (seller_rating DESC),
    FULLTEXT(business_name, description)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS products (
    product_id INT PRIMARY KEY AUTO_INCREMENT,
    seller_id INT NOT NULL,
    brand_id INT,
    product_name VARCHAR(255) NOT NULL,
    product_slug VARCHAR(255) UNIQUE NOT NULL,
    product_name_local VARCHAR(255),
    short_description TEXT,
    full_description LONGTEXT,
    specifications JSON,
    key_features JSON,
    category_id INT NOT NULL,
    subcategory_id INT,
    product_type ENUM('physical', 'digital', 'service', 'subscription') DEFAULT 'physical',
    sku VARCHAR(100) UNIQUE NOT NULL,
    barcode VARCHAR(50),
    weight_grams INT,
    dimensions JSON,
    price DECIMAL(12,2) NOT NULL,
    compare_at_price DECIMAL(12,2),
    cost_price DECIMAL(12,2),
    currency VARCHAR(3) DEFAULT 'VND',
    stock_quantity INT DEFAULT 0,
    track_inventory BOOLEAN DEFAULT TRUE,
    low_stock_threshold INT DEFAULT 10,
    allow_backorder BOOLEAN DEFAULT FALSE,
    shipping_required BOOLEAN DEFAULT TRUE,
    shipping_weight_grams INT,
    shipping_dimensions JSON,
    shipping_class VARCHAR(50),
    tax_class VARCHAR(50),
    tax_rate DECIMAL(5,2) DEFAULT 0,
    images JSON,
    featured_image VARCHAR(255),
    video_url VARCHAR(500),
    360_view_url VARCHAR(500),
    is_eco_friendly BOOLEAN DEFAULT FALSE,
    sustainability_score INT DEFAULT 0,
    eco_certifications JSON,
    carbon_footprint_kg DECIMAL(10,3),
    recyclable_percentage DECIMAL(5,2),
    biodegradable BOOLEAN DEFAULT FALSE,
    packaging_info JSON,
    materials_used JSON,
    origin_country VARCHAR(50),
    manufacturing_process TEXT,
    environmental_benefits TEXT,
    lifecycle_assessment JSON,
    certifications JSON,
    awards JSON,
    ingredients JSON,
    allergen_info JSON,
    age_group ENUM('all_ages', 'children', 'teens', 'adults', 'seniors') DEFAULT 'all_ages',
    gender_target ENUM('unisex', 'male', 'female') DEFAULT 'unisex',
    tags JSON,
    related_products JSON,
    frequently_bought_together JSON,
    cross_sell_products JSON,
    upsell_products JSON,
    variants JSON,
    custom_fields JSON,
    status ENUM('draft', 'active', 'inactive', 'out_of_stock', 'discontinued') DEFAULT 'draft',
    visibility ENUM('public', 'private', 'password_protected', 'members_only') DEFAULT 'public',
    featured BOOLEAN DEFAULT FALSE,
    featured_until TIMESTAMP NULL,
    search_keywords JSON,
    seo_title VARCHAR(255),
    seo_description TEXT,
    seo_keywords JSON,
    social_sharing_image VARCHAR(255),
    view_count INT DEFAULT 0,
    wishlist_count INT DEFAULT 0,
    sales_count INT DEFAULT 0,
    rating_average DECIMAL(3,2) DEFAULT 0,
    review_count INT DEFAULT 0,
    question_count INT DEFAULT 0,
    points_reward INT DEFAULT 0,
    loyalty_points_value INT DEFAULT 0,
    min_order_quantity INT DEFAULT 1,
    max_order_quantity INT,
    bulk_pricing JSON,
    volume_discounts JSON,
    seasonal_availability JSON,
    launch_date DATE,
    discontinued_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_seller_status (seller_id, status),
    INDEX idx_category_featured (category_id, featured, status),
    INDEX idx_eco_score (is_eco_friendly, sustainability_score DESC),
    INDEX idx_price_range (price, status),
    INDEX idx_stock (stock_quantity, status),
    INDEX idx_rating (rating_average DESC, review_count DESC),
    INDEX idx_slug (product_slug),
    FULLTEXT(product_name, short_description, full_description, tags, search_keywords)
) ENGINE=InnoDB;

-- ========================================
-- PHASE 10: E-COMMERCE REVIEWS & SHOPPING
-- ========================================

CREATE TABLE IF NOT EXISTS product_reviews (
    review_id INT PRIMARY KEY AUTO_INCREMENT,
    product_id INT NOT NULL,
    user_id INT NOT NULL,
    order_id INT,
    reviewer_name VARCHAR(100) NOT NULL,
    reviewer_email VARCHAR(100),
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    title VARCHAR(255),
    review_text TEXT,
    pros TEXT,
    cons TEXT,
    usage_duration ENUM('less_than_week', 'week_to_month', 'month_to_3months', '3months_to_year', 'over_year') DEFAULT 'less_than_week',
    purchase_verified BOOLEAN DEFAULT FALSE,
    recommended BOOLEAN DEFAULT TRUE,
    eco_rating INT CHECK (eco_rating BETWEEN 1 AND 5),
    eco_feedback TEXT,
    packaging_rating INT CHECK (packaging_rating BETWEEN 1 AND 5),
    delivery_rating INT CHECK (delivery_rating BETWEEN 1 AND 5),
    value_for_money_rating INT CHECK (value_for_money_rating BETWEEN 1 AND 5),
    images JSON,
    video_url VARCHAR(500),
    helpful_votes INT DEFAULT 0,
    unhelpful_votes INT DEFAULT 0,
    spam_reports INT DEFAULT 0,
    moderation_status ENUM('pending', 'approved', 'rejected', 'flagged') DEFAULT 'pending',
    moderation_notes TEXT,
    response_from_seller TEXT,
    seller_response_date TIMESTAMP NULL,
    featured BOOLEAN DEFAULT FALSE,
    verified_purchase BOOLEAN DEFAULT FALSE,
    incentivized BOOLEAN DEFAULT FALSE,
    source VARCHAR(50) DEFAULT 'website',
    ip_address VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_product_approved (product_id, moderation_status, created_at DESC),
    INDEX idx_user_reviews (user_id, created_at DESC),
    INDEX idx_rating_helpful (rating, helpful_votes DESC),
    INDEX idx_verified_featured (verified_purchase, featured),
    UNIQUE KEY unique_user_product_order (user_id, product_id, order_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS shopping_carts (
    cart_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    session_id VARCHAR(255),
    cart_token VARCHAR(255) UNIQUE NOT NULL,
    cart_status ENUM('active', 'abandoned', 'converted', 'recovered') DEFAULT 'active',
    total_items INT DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    shipping_amount DECIMAL(12,2) DEFAULT 0,
    total_amount DECIMAL(12,2) DEFAULT 0,
    currency VARCHAR(3) DEFAULT 'VND',
    coupon_codes JSON,
    applied_discounts JSON,
    shipping_address JSON,
    billing_address JSON,
    shipping_method VARCHAR(100),
    payment_method VARCHAR(100),
    notes TEXT,
    abandoned_at TIMESTAMP NULL,
    recovery_emails_sent INT DEFAULT 0,
    last_recovery_email TIMESTAMP NULL,
    converted_to_order_id INT,
    ip_address VARCHAR(45),
    user_agent TEXT,
    source VARCHAR(100),
    utm_parameters JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_status (user_id, cart_status),
    INDEX idx_session (session_id),
    INDEX idx_abandoned (abandoned_at, recovery_emails_sent),
    INDEX idx_token (cart_token)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cart_items (
    cart_item_id INT PRIMARY KEY AUTO_INCREMENT,
    cart_id INT NOT NULL,
    product_id INT NOT NULL,
    variant_id INT,
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(12, 2) NOT NULL,
    discount_amount DECIMAL(12, 2) DEFAULT 0,
    tax_amount DECIMAL(10, 2) DEFAULT 0,
    total_price DECIMAL(12, 2) NOT NULL,
    customization_data JSON,
    gift_wrap BOOLEAN DEFAULT FALSE,
    gift_message TEXT,
    saved_for_later BOOLEAN DEFAULT FALSE,
    added_from VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_cart_items (cart_id),
    INDEX idx_product (product_id),
    INDEX idx_saved_for_later (cart_id, saved_for_later),
    UNIQUE KEY unique_cart_product (cart_id, product_id, variant_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
    order_id INT PRIMARY KEY AUTO_INCREMENT,
    order_number VARCHAR(50) UNIQUE NOT NULL,
    user_id INT NOT NULL,
    seller_id INT NOT NULL,
    cart_id INT,
    customer_name VARCHAR(100) NOT NULL,
    customer_email VARCHAR(100) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    shipping_address JSON NOT NULL,
    billing_address JSON,
    shipping_method VARCHAR(100) NOT NULL,
    shipping_provider VARCHAR(100),
    shipping_tracking_number VARCHAR(100),
    shipping_tracking_url VARCHAR(500),
    shipping_cost DECIMAL(10, 2) DEFAULT 0,
    shipping_discount DECIMAL(10, 2) DEFAULT 0,
    estimated_delivery_date DATE,
    actual_delivery_date DATE,
    payment_method VARCHAR(100) NOT NULL,
    payment_provider VARCHAR(100),
    payment_transaction_id VARCHAR(100),
    payment_details JSON,
    subtotal DECIMAL(12, 2) NOT NULL,
    discount_amount DECIMAL(12, 2) DEFAULT 0,
    tax_amount DECIMAL(12, 2) DEFAULT 0,
    shipping_amount DECIMAL(12, 2) DEFAULT 0,
    total_amount DECIMAL(12, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'VND',
    coupon_codes JSON,
    applied_discounts JSON,
    order_status ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded', 'returned') DEFAULT 'pending',
    payment_status ENUM('pending', 'paid', 'failed', 'refunded', 'partially_refunded') DEFAULT 'pending',
    fulfillment_status ENUM('pending', 'processing', 'shipped', 'delivered', 'returned', 'cancelled') DEFAULT 'pending',
    notes TEXT,
    internal_notes TEXT,
    gift_order BOOLEAN DEFAULT FALSE,
    gift_message TEXT,
    priority ENUM('normal', 'high', 'urgent') DEFAULT 'normal',
    source VARCHAR(100) DEFAULT 'website',
    utm_parameters JSON,
    ip_address VARCHAR(45),
    user_agent TEXT,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP NULL,
    shipped_at TIMESTAMP NULL,
    delivered_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_orders (user_id, ordered_at DESC),
    INDEX idx_seller_orders (seller_id, order_status),
    INDEX idx_order_status (order_status, ordered_at DESC),
    INDEX idx_payment_status (payment_status),
    INDEX idx_tracking (shipping_tracking_number)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    seller_id INT NOT NULL,
    variant_id INT,
    product_name VARCHAR(255) NOT NULL,
    product_sku VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(12, 2) NOT NULL,
    discount_amount DECIMAL(12, 2) DEFAULT 0,
    tax_amount DECIMAL(10, 2) DEFAULT 0,
    total_price DECIMAL(12, 2) NOT NULL,
    commission_amount DECIMAL(12, 2) DEFAULT 0,
    customization_data JSON,
    gift_wrap BOOLEAN DEFAULT FALSE,
    fulfillment_status ENUM('pending', 'processing', 'shipped', 'delivered', 'returned', 'cancelled') DEFAULT 'pending',
    tracking_number VARCHAR(100),
    shipped_at TIMESTAMP NULL,
    delivered_at TIMESTAMP NULL,
    return_requested BOOLEAN DEFAULT FALSE,
    return_approved BOOLEAN DEFAULT FALSE,
    return_reason TEXT,
    refund_amount DECIMAL(12, 2) DEFAULT 0,
    refund_status ENUM('none', 'requested', 'approved', 'processed') DEFAULT 'none',
    review_reminder_sent BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_order_items (order_id),
    INDEX idx_product_orders (product_id),
    INDEX idx_seller_items (seller_id, fulfillment_status),
    INDEX idx_review_reminder (order_id, review_reminder_sent, delivered_at)
) ENGINE=InnoDB;

-- ========================================
-- PHASE 11: QUIZ & GAMIFICATION SYSTEM
-- ========================================

CREATE TABLE IF NOT EXISTS quiz_categories (
    category_id INT PRIMARY KEY AUTO_INCREMENT,
    category_name VARCHAR(100) NOT NULL,
    category_slug VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    icon_url VARCHAR(255),
    banner_image VARCHAR(255),
    difficulty_levels JSON DEFAULT '["beginner", "intermediate", "advanced"]',
    question_count INT DEFAULT 0,
    total_attempts INT DEFAULT 0,
    average_score DECIMAL(5,2) DEFAULT 0,
    pass_threshold INT DEFAULT 70,
    time_limit_minutes INT DEFAULT 30,
    attempts_allowed INT DEFAULT 3,
    shuffle_questions BOOLEAN DEFAULT TRUE,
    shuffle_answers BOOLEAN DEFAULT TRUE,
    show_correct_answers BOOLEAN DEFAULT TRUE,
    immediate_feedback BOOLEAN DEFAULT FALSE,
    certificate_template VARCHAR(255),
    points_per_question INT DEFAULT 10,
    bonus_points INT DEFAULT 50,
    is_featured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    requires_login BOOLEAN DEFAULT TRUE,
    min_age INT DEFAULT 0,
    max_age INT DEFAULT 100,
    prerequisites JSON,
    learning_objectives JSON,
    related_articles JSON,
    external_resources JSON,
    created_by INT NOT NULL,
    sort_order INT DEFAULT 0,
    seo_title VARCHAR(255),
    seo_description TEXT,
    seo_keywords JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_active_featured (is_active, is_featured, sort_order),
    INDEX idx_slug (category_slug),
    FULLTEXT(category_name, description)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS quiz_questions (
    question_id INT PRIMARY KEY AUTO_INCREMENT,
    category_id INT NOT NULL,
    question_text TEXT NOT NULL,
    question_text_en TEXT,
    question_type ENUM('multiple_choice', 'true_false', 'fill_blank', 'image_based', 'ordering', 'matching', 'essay') DEFAULT 'multiple_choice',
    question_image VARCHAR(255),
    question_audio VARCHAR(255),
    question_video VARCHAR(255),
    options JSON NOT NULL,
    correct_answer VARCHAR(255) NOT NULL,
    explanation TEXT,
    explanation_image VARCHAR(255),
    explanation_video VARCHAR(255),
    difficulty_level ENUM('beginner', 'intermediate', 'advanced') DEFAULT 'beginner',
    points_value INT DEFAULT 10,
    time_limit_seconds INT DEFAULT 60,
    hint_text TEXT,
    hint_penalty_points INT DEFAULT 2,
    category_tags JSON,
    learning_objective VARCHAR(255),
    bloom_taxonomy_level ENUM('remember', 'understand', 'apply', 'analyze', 'evaluate', 'create') DEFAULT 'remember',
    source_reference VARCHAR(255),
    author_notes TEXT,
    usage_count INT DEFAULT 0,
    correct_rate DECIMAL(5,2) DEFAULT 0,
    average_time_seconds DECIMAL(8,2) DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    is_verified BOOLEAN DEFAULT FALSE,
    created_by INT NOT NULL,
    reviewed_by INT,
    reviewed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_category_difficulty (category_id, difficulty_level, is_active),
    INDEX idx_type_difficulty (question_type, difficulty_level),
    INDEX idx_usage_stats (usage_count DESC, correct_rate),
    FULLTEXT(question_text, explanation, hint_text)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS quiz_sessions (
    session_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    category_id INT NOT NULL,
    quiz_type ENUM('practice', 'test', 'challenge', 'tournament', 'adaptive') DEFAULT 'practice',
    session_token VARCHAR(255) UNIQUE NOT NULL,
    total_questions INT NOT NULL,
    questions_answered INT DEFAULT 0,
    current_question_index INT DEFAULT 0,
    score INT DEFAULT 0,
    max_possible_score INT NOT NULL,
    score_percentage DECIMAL(5,2) DEFAULT 0,
    time_limit_seconds INT,
    time_taken_seconds INT DEFAULT 0,
    time_remaining_seconds INT,
    hints_used INT DEFAULT 0,
    incorrect_answers INT DEFAULT 0,
    status ENUM('started', 'in_progress', 'completed', 'abandoned', 'expired') DEFAULT 'started',
    completion_percentage DECIMAL(5,2) DEFAULT 0,
    passed BOOLEAN DEFAULT FALSE,
    certificate_issued BOOLEAN DEFAULT FALSE,
    certificate_url VARCHAR(500),
    points_earned INT DEFAULT 0,
    bonus_points INT DEFAULT 0,
    streak_count INT DEFAULT 0,
    difficulty_adjustment JSON,
    question_sequence JSON NOT NULL,
    answers_given JSON,
    performance_analytics JSON,
    start_ip VARCHAR(45),
    user_agent TEXT,
    device_info JSON,
    cheating_flags JSON,
    proctoring_data JSON,
    feedback_rating INT,
    feedback_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    expired_at TIMESTAMP NULL,
    INDEX idx_user_status (user_id, status),
    INDEX idx_user_category_date (user_id, category_id, created_at DESC),
    INDEX idx_leaderboard (quiz_type, score_percentage DESC, time_taken_seconds),
    INDEX idx_completed_date (completed_at),
    INDEX idx_session_token (session_token)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS quiz_responses (
    response_id INT PRIMARY KEY AUTO_INCREMENT,
    session_id INT NOT NULL,
    question_id INT NOT NULL,
    question_order INT NOT NULL,
    user_answer VARCHAR(255),
    is_correct BOOLEAN NOT NULL,
    points_earned INT DEFAULT 0,
    points_possible INT NOT NULL,
    time_taken_seconds INT NOT NULL,
    hint_used BOOLEAN DEFAULT FALSE,
    hint_penalty_applied INT DEFAULT 0,
    attempt_number INT DEFAULT 1,
    confidence_level ENUM('very_confident', 'confident', 'unsure', 'guessing') DEFAULT 'confident',
    thought_process TEXT,
    flagged_for_review BOOLEAN DEFAULT FALSE,
    reviewed_later BOOLEAN DEFAULT FALSE,
    difficulty_perceived ENUM('very_easy', 'easy', 'medium', 'hard', 'very_hard') DEFAULT 'medium',
    feedback_helpful BOOLEAN DEFAULT TRUE,
    answer_changed BOOLEAN DEFAULT FALSE,
    answer_history JSON,
    interaction_data JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_session_order (session_id, question_order),
    INDEX idx_question_performance (question_id, is_correct, time_taken_seconds),
    INDEX idx_session_analysis (session_id, is_correct, points_earned),
    UNIQUE KEY unique_session_question (session_id, question_id)
) ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS = 1;

-- ========================================
-- SAMPLE DATA FOR PHASE 7-11
-- ========================================

-- Sample Events
INSERT IGNORE INTO events (title, slug, description, event_type, event_mode, organizer_id, venue_name, venue_address, start_date, end_date, max_participants, registration_fee, status, tags, points_reward) VALUES
('Workshop Tái chế Sáng tạo', 'workshop-tai-che-sang-tao', 'Học cách biến rác thải thành đồ dùng hữu ích', 'workshop', 'offline', 1, 'Trung tâm Môi trường TP.HCM', '123 Nguyễn Văn Cừ, Q1, TP.HCM', DATE_ADD(NOW(), INTERVAL 7 DAY), DATE_ADD(NOW(), INTERVAL 7 DAY), 30, 50000, 'published', '["tái chế", "workshop", "sáng tạo"]', 25),
('Chiến dịch Dọn rác Bãi biển', 'chien-dich-don-rac-bai-bien', 'Cùng nhau làm sạch bãi biển Vũng Tàu', 'cleanup', 'offline', 2, 'Bãi biển Vũng Tàu', 'Bãi Trước, Vũng Tàu', DATE_ADD(NOW(), INTERVAL 14 DAY), DATE_ADD(NOW(), INTERVAL 14 DAY), 100, 0, 'published', '["dọn rác", "biển", "môi trường"]', 50),
('Hội thảo Online: Năng lượng Xanh', 'hoi-thao-nang-luong-xanh', 'Tìm hiểu về các giải pháp năng lượng tái tạo', 'conference', 'online', 1, 'Zoom Meeting', 'https://zoom.us/meeting123', DATE_ADD(NOW(), INTERVAL 21 DAY), DATE_ADD(NOW(), INTERVAL 21 DAY), 200, 0, 'published', '["năng lượng", "online", "hội thảo"]', 30);

-- Sample Event Registrations
INSERT IGNORE INTO event_registrations (event_id, user_id, registration_number, registration_status, payment_status, points_earned) VALUES
(1, 1, 'REG-001-001', 'registered', 'paid', 25),
(1, 2, 'REG-001-002', 'registered', 'paid', 25),
(2, 1, 'REG-002-001', 'registered', 'paid', 50),
(3, 2, 'REG-003-001', 'registered', 'paid', 30);

-- Sample Petitions
INSERT IGNORE INTO petitions (title, slug, summary, description, petition_type, target_type, target_entities, creator_id, signature_goal, status, tags, location_scope) VALUES
(
    'Cấm sử dụng túi nilon tại các siêu thị',
    'cam-tui-nilon-sieu-thi',
    'Kêu gọi các siêu thị ngừng cung cấp túi nilon miễn phí để giảm ô nhiễm môi trường',
    'Túi nilon là một trong những nguyên nhân chính gây ô nhiễm môi trường. Chúng ta cần hành động ngay để bảo vệ hành tinh xanh.',
    'environmental',
    'corporation',
    '["Big C", "Lotte Mart", "Co.opmart", "Saigon Co.op"]',
    1,
    10000,
    'active',
    '["túi nilon", "siêu thị", "môi trường"]',
    'national'
),
(
    'Tăng cường trồng cây xanh trong thành phố',
    'tang-cuong-trong-cay-xanh',
    'Đề nghị chính quyền địa phương tăng diện tích cây xanh để cải thiện chất lượng không khí',
    'Thành phố cần nhiều cây xanh hơn để chống lại ô nhiễm không khí và tạo không gian sống thoáng mát.',
    'policy',
    'government',
    '["UBND TP.HCM", "Sở Tài nguyên Môi trường"]',
    2,
    5000,
    'active',
    '["cây xanh", "chính sách", "không khí"]',
    'city'
);

-- Sample Petition Signatures
INSERT IGNORE INTO petition_signatures (petition_id, user_id, signer_name, signer_email, signer_city, is_verified, verification_method) VALUES
(1, 1, 'Nguyễn Admin', 'admin@example.com', 'TP. Hồ Chí Minh', TRUE, 'email'),
(1, 2, 'Trần Eco User', 'eco@example.com', 'TP. Hồ Chí Minh', TRUE, 'email'),
(2, 1, 'Nguyễn Admin', 'admin@example.com', 'TP. Hồ Chí Minh', TRUE, 'email');

-- Sample Product Brands
INSERT IGNORE INTO product_brands (brand_name, brand_slug, description, sustainability_score, eco_certifications, is_verified, is_active) VALUES
('EcoLife Vietnam', 'ecolife-vietnam', 'Thương hiệu sản phẩm xanh hàng đầu Việt Nam', 95, '["FSC", "USDA Organic", "Fair Trade"]', TRUE, TRUE),
('Green Home', 'green-home', 'Đồ gia dụng thân thiện môi trường', 88, '["Energy Star", "EPEAT"]', TRUE, TRUE),
('Bamboo World', 'bamboo-world', 'Sản phẩm tre tự nhiên 100%', 92, '["Organic", "Biodegradable"]', TRUE, TRUE);

-- Sample Sellers
INSERT IGNORE INTO sellers (user_id, brand_id, business_name, business_type, description, contact_email, contact_phone, account_status, verification_status) VALUES
(1, 1, 'EcoLife Store Official', 'company', 'Cửa hàng chính thức của thương hiệu EcoLife', 'store@ecolife.vn', '0901234567', 'active', 'verified'),
(2, 2, 'Green Home Shop', 'individual', 'Chuyên bán đồ gia dụng xanh', 'info@greenhome.vn', '0907654321', 'active', 'verified');

-- Sample Products
INSERT IGNORE INTO products (seller_id, brand_id, product_name, product_slug, short_description, full_description, category_id, sku, price, stock_quantity, is_eco_friendly, sustainability_score, status) VALUES
(1, 1, 'Túi vải hữu cơ EcoLife', 'tui-vai-huu-co-ecolife', 'Túi vải cotton hữu cơ có thể tái sử dụng', 'Túi vải cotton 100% hữu cơ, không sử dụng hóa chất, có thể giặt và tái sử dụng nhiều lần. Thay thế hoàn hảo cho túi nilon.', 1, 'ECO-BAG-001', 150000, 100, TRUE, 98, 'active'),
(2, 2, 'Hộp cơm tre tự nhiên', 'hop-com-tre-tu-nhien', 'Hộp đựng thức ăn từ tre 100% tự nhiên', 'Hộp cơm làm từ tre tự nhiên, không chứa BPA, an toàn cho sức khỏe, có thể phân hủy sinh học.', 1, 'BAMBOO-BOX-001', 280000, 50, TRUE, 95, 'active'),
(1, 3, 'Ống hút tre thay thế', 'ong-hut-tre-thay-the', 'Bộ ống hút tre tái sử dụng', 'Bộ 6 ống hút tre với cọ rửa, thay thế ống hút nhựa một cách hoàn hảo, bảo vệ môi trường.', 1, 'BAMBOO-STRAW-001', 45000, 200, TRUE, 99, 'active');

-- Sample Shopping Carts
INSERT IGNORE INTO shopping_carts (user_id, cart_token, total_items, subtotal, total_amount, cart_status) VALUES
(1, 'CART-TOKEN-001', 2, 430000, 430000, 'active'),
(2, 'CART-TOKEN-002', 1, 150000, 150000, 'active');

-- Sample Cart Items
INSERT IGNORE INTO cart_items (cart_id, product_id, quantity, unit_price, total_price) VALUES
(1, 1, 1, 150000, 150000),
(1, 2, 1, 280000, 280000),
(2, 3, 1, 45000, 45000);

-- Sample Quiz Categories
INSERT IGNORE INTO quiz_categories (category_name, category_slug, description, question_count, pass_threshold, time_limit_minutes, created_by, is_active) VALUES
('Kiến thức Môi trường Cơ bản', 'kien-thuc-moi-truong-co-ban', 'Các câu hỏi cơ bản về bảo vệ môi trường', 20, 70, 30, 1, TRUE),
('Tái chế và Xử lý Rác thải', 'tai-che-xu-ly-rac-thai', 'Kiến thức về tái chế và xử lý rác thải đúng cách', 15, 75, 25, 1, TRUE),
('Năng lượng Tái tạo', 'nang-luong-tai-tao', 'Hiểu biết về các nguồn năng lượng tái tạo', 18, 80, 35, 2, TRUE);

-- Sample Quiz Questions
INSERT IGNORE INTO quiz_questions (category_id, question_text, question_type, options, correct_answer, explanation, difficulty_level, points_value, created_by, is_active) VALUES
(1, 'Khí nào sau đây là nguyên nhân chính gây hiệu ứng nhà kính?', 'multiple_choice', '{"A": "Oxygen (O2)", "B": "Carbon Dioxide (CO2)", "C": "Nitrogen (N2)", "D": "Hydrogen (H2)"}', 'B', 'CO2 là khí nhà kính chính gây ra hiện tượng nóng lên toàn cầu', 'beginner', 10, 1, TRUE),
(1, 'Việc tái chế 1 tấn giấy có thể tiết kiệm được bao nhiêu cây?', 'multiple_choice', '{"A": "5-10 cây", "B": "10-15 cây", "C": "15-17 cây", "D": "20-25 cây"}', 'C', 'Tái chế 1 tấn giấy có thể tiết kiệm 15-17 cây trưởng thành', 'intermediate', 15, 1, TRUE),
(2, 'Thời gian phân hủy của túi nilon trong tự nhiên là bao lâu?', 'multiple_choice', '{"A": "10-20 năm", "B": "50-100 năm", "C": "200-500 năm", "D": "1000+ năm"}', 'C', 'Túi nilon cần 200-500 năm để phân hủy hoàn toàn trong tự nhiên', 'beginner', 10, 1, TRUE);

-- Update petition signature counts
UPDATE petitions SET current_signatures = (SELECT COUNT(*) FROM petition_signatures WHERE petition_signatures.petition_id = petitions.petition_id);

-- Update product review counts (placeholder since no reviews yet)
UPDATE products SET review_count = 0, rating_average = 0;

-- Update quiz category question counts
UPDATE quiz_categories SET question_count = (SELECT COUNT(*) FROM quiz_questions WHERE quiz_questions.category_id = quiz_categories.category_id AND is_active = TRUE);

SELECT 'Phase 7-11 Complete!' as status;
SELECT 'Advanced Features Added:' as info;
SELECT 
    (SELECT COUNT(*) FROM events) as total_events,
    (SELECT COUNT(*) FROM petitions) as total_petitions,
    (SELECT COUNT(*) FROM products) as total_products,
    (SELECT COUNT(*) FROM quiz_categories) as quiz_categories,
    (SELECT COUNT(*) FROM quiz_questions) as quiz_questions;
