-- Complete the Phase 20 tables creation
-- Add remaining columns to user_activities_comprehensive
ALTER TABLE user_activities_comprehensive 
ADD COLUMN activity_category VARCHAR(50) DEFAULT NULL,
ADD COLUMN activity_subcategory VARCHAR(100) DEFAULT NULL,
ADD COLUMN activity_name VARCHAR(200) DEFAULT NULL,
ADD COLUMN activity_description TEXT DEFAULT NULL,
ADD COLUMN carbon_impact_kg DECIMAL(10,3) DEFAULT 0.000,
ADD COLUMN environmental_score INT DEFAULT 0,
ADD COLUMN sustainability_points INT DEFAULT 0,
ADD COLUMN engagement_score DECIMAL(8,2) DEFAULT 0.00,
ADD COLUMN quality_score DECIMAL(5,2) DEFAULT 0.00,
ADD COLUMN base_points INT DEFAULT 0,
ADD COLUMN bonus_points INT DEFAULT 0,
ADD COLUMN streak_bonus INT DEFAULT 0,
ADD COLUMN total_points INT DEFAULT 0,
ADD COLUMN is_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Create user_streaks_advanced table
CREATE TABLE IF NOT EXISTS user_streaks_advanced (
    streak_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    streak_type VARCHAR(50) NOT NULL,
    streak_category VARCHAR(50) NOT NULL,
    current_streak INT DEFAULT 0,
    longest_streak INT DEFAULT 0,
    total_activities INT DEFAULT 0,
    freeze_cards_used INT DEFAULT 0,
    freeze_cards_remaining INT DEFAULT 3,
    grace_period_hours INT DEFAULT 24,
    last_activity_date DATE DEFAULT NULL,
    milestone_rewards_earned INT DEFAULT 0,
    current_multiplier DECIMAL(3,2) DEFAULT 1.00,
    max_multiplier_reached DECIMAL(3,2) DEFAULT 1.00,
    bonus_points_earned INT DEFAULT 0,
    total_carbon_saved_kg DECIMAL(10,3) DEFAULT 0.000,
    environmental_actions_count INT DEFAULT 0,
    sustainability_impact_score INT DEFAULT 0,
    influenced_users_count INT DEFAULT 0,
    community_contributions INT DEFAULT 0,
    collaborative_streaks INT DEFAULT 0,
    streak_breaks_count INT DEFAULT 0,
    longest_break_days INT DEFAULT 0,
    recovery_speed_avg_days DECIMAL(5,2) DEFAULT 0.00,
    consistency_score DECIMAL(5,2) DEFAULT 0.00,
    improvement_rate DECIMAL(5,2) DEFAULT 0.00,
    performance_trend VARCHAR(20) DEFAULT 'stable',
    streak_started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Create user_engagement_scores table
CREATE TABLE IF NOT EXISTS user_engagement_scores (
    score_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    score_period VARCHAR(20) NOT NULL,
    period_start_date DATE NOT NULL,
    period_end_date DATE NOT NULL,
    activity_frequency_score DECIMAL(5,2) DEFAULT 0.00,
    activity_diversity_score DECIMAL(5,2) DEFAULT 0.00,
    quality_score DECIMAL(5,2) DEFAULT 0.00,
    consistency_score DECIMAL(5,2) DEFAULT 0.00,
    innovation_score DECIMAL(5,2) DEFAULT 0.00,
    collaboration_score DECIMAL(5,2) DEFAULT 0.00,
    community_influence_score DECIMAL(5,2) DEFAULT 0.00,
    leadership_score DECIMAL(5,2) DEFAULT 0.00,
    environmental_impact_score DECIMAL(5,2) DEFAULT 0.00,
    sustainability_commitment_score DECIMAL(5,2) DEFAULT 0.00,
    overall_engagement_score DECIMAL(6,2) DEFAULT 0.00,
    weighted_composite_score DECIMAL(6,2) DEFAULT 0.00,
    user_rank_in_period INT DEFAULT NULL,
    percentile_rank DECIMAL(5,2) DEFAULT 0.00,
    total_users_in_period INT DEFAULT 0,
    score_change_from_previous DECIMAL(6,2) DEFAULT 0.00,
    trend_direction VARCHAR(20) DEFAULT 'stable',
    momentum_indicator DECIMAL(5,2) DEFAULT 0.00,
    primary_activity_focus VARCHAR(100) DEFAULT NULL,
    engagement_pattern VARCHAR(50) DEFAULT NULL,
    motivation_factors TEXT DEFAULT NULL,
    churn_risk_score DECIMAL(5,2) DEFAULT 0.00,
    engagement_volatility DECIMAL(5,2) DEFAULT 0.00,
    growth_potential_score DECIMAL(5,2) DEFAULT 0.00,
    recommended_actions TEXT DEFAULT NULL,
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Create user_activity_patterns table
CREATE TABLE IF NOT EXISTS user_activity_patterns (
    pattern_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    analysis_period VARCHAR(20) NOT NULL,
    analysis_start_date DATE NOT NULL,
    analysis_end_date DATE NOT NULL,
    primary_activity_times TEXT DEFAULT NULL,
    preferred_activity_types TEXT DEFAULT NULL,
    session_length_patterns TEXT DEFAULT NULL,
    weekly_activity_distribution TEXT DEFAULT NULL,
    seasonal_patterns TEXT DEFAULT NULL,
    device_usage_patterns TEXT DEFAULT NULL,
    location_patterns TEXT DEFAULT NULL,
    social_interaction_patterns TEXT DEFAULT NULL,
    content_consumption_patterns TEXT DEFAULT NULL,
    engagement_decline_indicators TEXT DEFAULT NULL,
    productivity_peak_times TEXT DEFAULT NULL,
    behavioral_consistency_score DECIMAL(5,2) DEFAULT 0.00,
    pattern_stability_score DECIMAL(5,2) DEFAULT 0.00,
    predictability_index DECIMAL(5,2) DEFAULT 0.00,
    anomaly_detection_flags TEXT DEFAULT NULL,
    churn_risk_indicators TEXT DEFAULT NULL,
    growth_opportunity_areas TEXT DEFAULT NULL,
    personalization_recommendations TEXT DEFAULT NULL,
    next_likely_activities TEXT DEFAULT NULL,
    optimal_engagement_times TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Create user_habit_tracking table
CREATE TABLE IF NOT EXISTS user_habit_tracking (
    habit_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    habit_name VARCHAR(200) NOT NULL,
    habit_description TEXT DEFAULT NULL,
    habit_category VARCHAR(100) NOT NULL,
    target_frequency VARCHAR(50) DEFAULT 'daily',
    target_duration_minutes INT DEFAULT 0,
    habit_difficulty VARCHAR(20) DEFAULT 'medium',
    environmental_focus BOOLEAN DEFAULT FALSE,
    carbon_impact_per_completion DECIMAL(8,3) DEFAULT 0.000,
    sustainability_points_per_completion INT DEFAULT 0,
    habit_start_date DATE NOT NULL,
    current_streak INT DEFAULT 0,
    longest_streak INT DEFAULT 0,
    total_completions INT DEFAULT 0,
    success_rate DECIMAL(5,2) DEFAULT 0.00,
    automaticity_level DECIMAL(5,2) DEFAULT 0.00,
    habit_strength_score DECIMAL(5,2) DEFAULT 0.00,
    difficulty_perception DECIMAL(5,2) DEFAULT 5.00,
    motivation_level DECIMAL(5,2) DEFAULT 5.00,
    environmental_awareness_gain DECIMAL(5,2) DEFAULT 0.00,
    has_accountability_partner BOOLEAN DEFAULT FALSE,
    accountability_partner_user_id INT DEFAULT NULL,
    reminder_frequency VARCHAR(50) DEFAULT 'daily',
    reminder_enabled BOOLEAN DEFAULT TRUE,
    last_completed_date DATE DEFAULT NULL,
    next_due_date DATE DEFAULT NULL,
    completion_trend VARCHAR(20) DEFAULT 'stable',
    habit_status VARCHAR(20) DEFAULT 'active',
    milestone_rewards_earned INT DEFAULT 0,
    total_points_earned INT DEFAULT 0,
    notes TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (accountability_partner_user_id) REFERENCES users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB;
