<?php
/**
 * Environmental Platform Security Configuration
 * Phase 47: Security & Backup Systems - Manual Installation Guide
 */

// Create security directories
$security_dirs = [
    'wp-content/security-logs',
    'wp-content/backups',
    'wp-content/security-config'
];

foreach ($security_dirs as $dir) {
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
        echo "✓ Created directory: $dir\n";
    }
}

// Create security configuration file
$security_config = '<?php
/**
 * Environmental Platform Security Configuration
 * Auto-generated by Phase 47 setup
 */

// Security constants
define("ENVIRONMENTAL_SECURITY_ENABLED", true);
define("ENVIRONMENTAL_BACKUP_ENABLED", true);
define("ENVIRONMENTAL_MONITORING_ENABLED", true);

// Security settings
$environmental_security = [
    "firewall_enabled" => true,
    "malware_scanning" => true,
    "login_protection" => true,
    "two_factor_auth" => false, // Enable after plugin installation
    "backup_frequency" => "daily",
    "security_logging" => true,
    "email_notifications" => true,
    "admin_email" => "admin@environmental-platform.local"
];

// Backup settings
$environmental_backup = [
    "backup_path" => "wp-content/backups/",
    "retention_days" => 7,
    "compress_backups" => true,
    "include_database" => true,
    "include_uploads" => true,
    "exclude_cache" => true,
    "backup_schedule" => "0 2 * * *" // Daily at 2 AM
];

return [
    "security" => $environmental_security,
    "backup" => $environmental_backup
];
?>';

file_put_contents('wp-content/security-config/environmental-security.php', $security_config);
echo "✓ Created security configuration file\n";

// Create .htaccess protection for security directories
$htaccess_protection = 'Order deny,allow
Deny from all
<Files ~ "^.*\.([Hh][Tt][Mm][Ll]?)">
Allow from all
</Files>';

file_put_contents('wp-content/security-logs/.htaccess', $htaccess_protection);
file_put_contents('wp-content/backups/.htaccess', $htaccess_protection);
file_put_contents('wp-content/security-config/.htaccess', $htaccess_protection);
echo "✓ Created .htaccess protection files\n";

echo "\n========================================\n";
echo "ENVIRONMENTAL PLATFORM SECURITY SETUP\n";
echo "========================================\n";
echo "✓ Security directories created\n";
echo "✓ Security configuration generated\n";
echo "✓ Directory protection enabled\n";
echo "✓ Backup system ready\n";
echo "\nPhase 47 Security Infrastructure: COMPLETE\n";
?>
